tshark: start working on update to 3.0.0
fails with /storage/termux-build/_cache/19b-aarch64-21-v1/lib64/clang/8.0.2/include/mmintrin.h:64:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);